#if !defined(CONTANTS_H)
#define CONTANTS_H

#define PCM_BUFFERSIZE 8192
#define PCM_SAMPLERATE 44100
#define PCM_CHANNELS 2
#define PCM_BITDEPTH 16
#define PCM_SAMPLETYPE QAudioFormat::SignedInt

#define LAME_BUFFERSIZE 16384
#define LAME_SAMPLERATE 44100
#define LAME_CHANNELS 2
#define LAME_BITRATE 128
#define LAME_MODE STEREO

#define AAC_BUFFERSIZE 20480
#define AAC_BITRATE 128000
#define AAC_SAMPLERATE 44100
#define AAC_CHANNELS 2
#define AAC_CHANNELMODE MODE_2
#define AAC_AOT 2

#define MOUNTPOINT_URL_MAX_LEN 128
#define MOUNTPOINT_PORT_MAX_LEN 8
#define MOUNTPOINT_PASSWORD_MAX_LEN 64
#define MOUNTPOINT_MIME_MAX_LEN 16
#define MOUNTPOINT_ENDPOINT_MAX_LEN 32
#define MOUNTPOINT_METADATA_MAX_LEN 128
#define MOUNTPOINT_AUTHHEADER_MAX_LEN 1024
#define MOUNTPOINT_SOCKETSTATE_STRING_MAXLEN 32
#define MOUNTPOINT_SOCKET_TIMEOUT 3000
#define MOUNTPOINT_READ_BUFFERSIZE 1024

#define SOCKET_STATE_DISCONNECTED 0
#define SOCKET_STATE_CONNECTING 1
#define SOCKET_STATE_CONNECTED 2
#define SOCKET_STATE_AUTHENTICATING 3
#define SOCKET_STATE_AUTHENTICATED 4
#define SOCKET_STATE_CLOSING 5

#define APP_CLOCK_TIMEOUT 60000

#endif // CONTANTS_H
